spring.application.name=bulktransactionservice
server.port=8083

## = DATA SOURCE LOCAL
## ===============================
spring.datasource.url = jdbc:mysql://localhost:3306/transactions
spring.datasource.username = root
spring.datasource.password = Muyiwa123!
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jwt config
jwt.secret=X9VYx4pV0ymYMy1qgRZ6LQWKi4hX8xWTu4w5VgWPHlM=
jwt.expiration-ms=3600000

# --- Retry Configuration ---
resilience4j.retry.instances.transactionServiceRetry.max-attempts=3
resilience4j.retry.instances.transactionServiceRetry.wait-duration=1s

# --- Circuit Breaker Configuration ---
resilience4j.circuitbreaker.instances.transactionServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.transactionServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.transactionServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.transactionServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.transactionServiceCB.minimum-number-of-calls=5

# --- Time Limiter Configuration ---
resilience4j.timelimiter.instances.transactionServiceTimeout.timeout-duration=2s

# --- Logging for debugging ---
logging.level.io.github.resilience4j=DEBUG
logging.level.org.springframework.security=DEBUG

#transaction config
txn.service.url=http://transaction-service/api/v1/transactions

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

